name: HCPSS StoryStrong
description: Student and Staff stories from the Howard County Public School System.
url: http://storystrong.hcpss.org
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: "hcpss"
headshot-path: "/img/headshots/"
bg-path: "/img/bg/"

# Build settings
markdown: kramdown
permalink: /stories/:title/

# Pagination settings
paginate: 8
paginate_path: "/stories/page:num/"

exclude:
  - Gemfile
  - Gemfile.lock
  - [Guardfile]
  - node_modules