baseurl: "/story-strong/" # the subpath of your site, e.g. /blog
twitter_username: "hcpss-storystrong"

# Build settings
markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - [Guardfile]
  - node_modules