baseurl: "/story-strong" # the subpath of your site, e.g. /blog
twitter_username: "hcpss"
headshot-path: "/story-strong/img/headshots/"
bg-path: "/story-strong/img/bg/"

# Build settings
markdown: kramdown
permalink: /stories/:title/

exclude:
  - Gemfile
  - Gemfile.lock
  - [Guardfile]
  - node_modules