name: HCPSS StoryStrong
description: Student and Staff stories from the Howard County Public School System.
url: https://storystrong.hcpss.org/
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: "hcpss"
headshot-path: "/img/headshots/"
bg-path: "/img/bg/"

# Build settings
markdown: kramdown
permalink: /stories/:title/

# Pagination settings
paginate: 8
paginate_path: "/stories/page:num/"

exclude:
  - Gemfile
  - Gemfile.lock
  - Guardfile
  - gulpfile.js
  - node_modules
  - package-lock.json
  - package.json
  - README.md
  - scss

plugins: [jekyll-paginate]
